# Generated by Django 4.0.1 on 2022-02-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_newuser_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_staff',
        ),
    ]
