# Generated by Django 4.0.1 on 2022-02-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='user_id',
            field=models.IntegerField(default='1'),
        ),
    ]
